{% set name = "persim" %}
{% set version = "0.1.2" %}
{% set sha256 = "564cc46f595dde7478511b1c268dc44c219dcee28b49222f79b09eac12d1e66f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - scikit-learn
    - numpy
    - matplotlib-base
    - scipy
    - hopcroftkarp

test:
  imports:
    - persim

about:
  home: http://github.com/scikit-tda/persim
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Distances and representations of persistence diagrams'

  description: |
    Persim is a Python package for many tools used in analyzing Persistence Diagrams. It currently houses implementations of Persistence Images, Bottleneck distance, Sliced Wasserstein Kernel, Heat Kernel, and Diagram plotting
  doc_url: http://persim.scikit-tda.org/
  dev_url: https://github.com/scikit-tda/persim

extra:
  recipe-maintainers:
    - sauln
    - bdice
