travis:
  secure:
    BINSTAR_TOKEN: i4/aQKfcQQ5nILzvUkunpLmxy/YSZDVO3HmG3oik08NDmStZifKK0XvcsLkYXMhZH7+sFNepEV2V7ffZUl1Px8SekUHlRLnpXjcVXzzs5ZvVK5yXtmqB7bPDDWV0iICRXzsqH7jh6Rzg3UPu36+xa+VhCZB9XtdkW6gBCEvHPLcPmG87+ilPtjhYvrRVllksLjo579NDRfxiKQKmRsWd1faxWIoGVqljdu5Eae1wM/7AnMU0MV5d4GvHLjFbW4riVqn1r1GND0yjQwpFd+QY7nuK7agZY4k3wWFF4QY/pMqH79Xz5hMnIdYA0IwA7Ezn9AmfagfwsuuCyfBHvyNkP4dwMZjoOYiY2/uE/JsGAXMYGkEzReRnONyQIxBOUBMRWLksVF9ICIfEnlWR8Hk+IFd9R4tLMgEhUxRUMjqZMTE0W++0xPYv70xJOOFv5kcBS+VJW/6+wmX/VErEHWkH9gdF/8QigTg+HiBDV88/z/89QvM0anUvsw3rynyKygg7YGeP9JYWTjnF+63sNQDco2VPOsk12RFmrc35IZa6SXAIlEZ2ppbqNqJdszu/8V6bYHAPY+ptV5MAZbOI9QaG2xe/rUDcTHqO2CH4gtwgHVsGSIwkTcw/O8T29eS2ESW9k0pPlmKjKBk045/zUwW+kQ3/H7NMbcl8ERFB+fwm0VQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
